name: Build and Push Docker Images

on:
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Docker Login
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # FRONT
      - name: Build Frontend Docker image
        working-directory: front
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest .

      - name: Push Frontend Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-front:latest

      # BACK
      - name: Build Backend Docker image
        working-directory: back
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest .

      - name: Push Backend Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/bobapp-back:latest
