name: Main Workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend-tests:
    uses: ./.github/workflows/node.js.yml

  backend-tests:
    needs: frontend-tests
    uses: ./.github/workflows/back.yml

  sonar-check:
    needs: backend-tests
    uses: ./.github/workflows/sonar.yml
    secrets: 
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker-publish:
    needs: sonar-check
    uses: ./.github/workflows/docker-publish.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }} 
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }} 
