name: Frontend Tests

on:
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - completed

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: front/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Build the app (optional)
      run: npm run build --if-present

    - name: Run tests with coverage
      run: npm test -- --watch=false --code-coverage

    - name: Upload test coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-coverage
        path: front/coverage
