name: SonarCloud Quality Gate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarcloud:
    name: Analyze with SonarCloud
    runs-on: ubuntu-latest

    steps:
      # Checkout du code source
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup JDK
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      # Cache des dépendances
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('front/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Installation des dépendances frontend et backend
      - name: Install dependencies
        run: |
          cd front && npm install
          cd backend && mvn install

      # Lancement de l'analyse SonarCloud
      - name: Run SonarCloud Analysis
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
